language: python

python: 3.6

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds

install:
  - "pip install -U pip"
  - "pip install Lektor"
  - "pip install fabric"

script: "lektor build"

deploy:
  - provider: script
    script: "lektor deploy develop"
    on:
       branch: develop

  - provider: script
    script: "lektor deploy production && python scripts/deploy.py"
    on:
       branch: production
