language: python

python: 3.6

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds

before_install:
  - curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.32.1/nvm.sh
  - source $HOME/.nvm/nvm.sh
  - nvm install stable
  - node --version

install:
  - "pip install -U pip"
  - "pip install -U Lektor"
  - "pip install -U fabric"
  - "lektor plugins reinstall"

script: "lektor build -f webpack --no-prune"

deploy:
  - provider: script
    script: "lektor deploy develop"
    on:
       branch: develop

  - provider: script
    script: "lektor deploy production && python scripts/deploy.py"
    on:
       branch: production
